name: mobility_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Firebase 
  firebase_core: ^1.15.0
  firebase_auth: ^3.3.15
  cloud_firestore: ^3.1.13

  #UX/UI
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  lottie: ^1.3.0

  #MAPS
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

 
